"""
Generate a simple API modules index for the `cullinan` package.
Writes output to `docs/work/api_modules.md`.
Run from repository root: python docs\work\generate_api_index.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PKG = ROOT / "cullinan"
OUT = ROOT / "docs" / "work" / "api_modules.md"

modules = []

for p in PKG.rglob('*.py'):
    if p.name == '__init__.py':
        # mark package
        pkg = p.parent.relative_to(ROOT).as_posix().replace('/', '.')
        modules.append((pkg, 'package'))
    else:
        rel = p.relative_to(ROOT).with_suffix('')
        mod = rel.as_posix().replace('/', '.')
        modules.append((mod, 'module'))

# Deduplicate and sort
seen = set()
clean = []
for m,t in modules:
    if m not in seen:
        seen.add(m)
        clean.append((m,t))
clean.sort()

lines = ["# API Modules Index", "", "This file is generated by `docs/work/generate_api_index.py`.", "", "Found modules/packages:", ""]
for m,t in clean:
    lines.append(f"- `{m}`  — {t}")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote API modules index to {OUT}")

